---
title: "1020_datawranglingII_m4"
author: "Yutian Luo"
date: "10/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(httr)
```


# Part I: reading data from web

## 1. read web to df
1. read_html()
2. html_nodes(css = )

```{r read web df}
url_drug = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"    # define url

drug_use_html = read_html(url_drug)   # define html, read url 

drug_use_html %>%                    # select table from readed html
  html_nodes(css = "table")

```



## 2. df table manipulation

1. first(),    select first table
2. html_table()     convert to df
3. slice()   remove 1st row
4. as_tibble()    convert to tibble, easy to view

```{r read table}
table_marj = 
  drug_use_html %>% 
  html_nodes(css = "table") %>%     # select table
  first() %>%            # select first table from web
  html_table() %>%       # convert to df
  slice(-1) %>%          # remove 1st row
  as_tibble()
  
view(table_marj)
```



### learning assess
Create a data frame that contains the cost of living table for New York from this page

1. html_nodes().[[i]]    start from row i

```{r read from website table}
nyc_living = 
  read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") %>% 
  html_nodes(css = "table") %>% 
  .[[1]] %>%       # start from the 1st row
  html_table(header = TRUE)
  
nyc_living
```



## 3. CSS selector


```{r}
star_war = 
  read_html("https://www.imdb.com/list/ls070150896/")
```










